version: "3.8"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    network_mode: "host"
    restart: always
    volumes:
      - ollama:/root/.ollama

  embedding:
    container_name: embedding-service
    build:
      context: ./services/embedding
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always

  codebase-guy:
    container_name: codebase-guy
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always

  postgres:
    image: ankane/pgvector:latest
    network_mode: "host"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: codebase-guy
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    network_mode: "host"
    volumes:
      - redisdata:/data
    restart: always

volumes:
  pgdata:
  redisdata:
  ollama:
