version: "3.8"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama:/root/.ollama

  embedding:
    container_name: embedding-service
    build:
      context: ./services/embedding
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: always

  codebaseguy:
    container_name: codebase-guy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

volumes:
  ollama:
